site_name: LLM自主智能体应用实战课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - LLM自主智能体应用实战课.md
  
   - 开篇词-天作之合：LLM助力业务流程自动化.md
  
   - 01-Autonomous Agent开发框架的爱丽丝奇境.md
  
   - 02-收拾行李，准备上路.md
  
   - 03-初识MetaGPT.md
  
   - 04-使用MetaGPT实现Autonomous Agent应用.md
  
   - 05-MetaGPT高级开发技能.md
  
   - 06-初识AutoGPT.md
  
   - 07-扫清AutoGPT开发道路上的障碍.md
  
   - 08-使用AutoGPT实现Autonomous Agent应用.md
  
   - 09-AutoGPT高级开发技能.md
  
   - 10-初识Swarm.md
  
   - 11-使用Swarm实现Autonomous Agent应用.md
  
   - 12-初识DSPy.md
  
   - 13-DSPy贴身实战.md
  
   - 14-如何设计Autonomous Agent应用？（上）.md
  
   - 15-如何设计Autonomous Agent应用？（下）.md
  
   - 16-行业应用需求：企业员工 AI 助理.md
  
   - 17-企业员工AI助理的架构设计.md
  
   - 18-企业员工AI助理开发前的扫雷工作.md
  
   - 19-企业员工AI助理编程：实现多Agent.md
  